services:
  nginx:
    extends:
      file: docker-compose.yml
      service: nginx

  torrserver:
    extends:
      file: docker-compose.yml
      service: torrserver
    build:
      dockerfile: Dockerfile
      context: ./torrserver
      args:
        - REACT_APP_SERVER_HOST=.
        - PUBLIC_URL=.
    image: '' # Override image with empty string to use build instead

  qbittorrent:
    extends:
      file: docker-compose.yml
      service: qbittorrent

  lampac-api:
    extends:
      file: docker-compose.yml
      service: lampac-api
  lampa:
    extends:
      file: docker-compose.yml
      service: lampa
    build:
      dockerfile: Dockerfile
      context: ./lampa
    image: '' # Override image with empty string to use build instead

  # Test services for nginx proxy debugging
  # echo:
  #   image: mendhak/http-https-echo:35
  #   restart: unless-stopped
  #   expose:
  #     - "8080"
  #     - "8443"

# Can't use extends at top level
volumes:
  torrserver-cache:
  torrserver-config:
  nginx-passwords:
  qbittorrent-config:
  qbittorrent-data:
