services:
  lampac:
    image: immisterio/lampac:latest
    restart: unless-stopped
    volumes:
      - ./docker/lampac/manifest.json:/home/module/manifest.json:ro
    expose:
      - "9118"
    labels: [ "com.centurylinklabs.watchtower.scope=lampac" ]
    entrypoint: ["/bin/sh", "-c", "echo '{\"frontend\": \"cloudflare\", \"puppeteer\": {\"executablePath\": \"/usr/bin/chromium\"}, \"localip\": false, \"listenhost\": \"${LAMPA_STACK_DOMAIN}\", \"listenscheme\": \"${LAMPA_STACK_SCHEME}\"}' > /home/init.conf && /usr/share/dotnet/dotnet Lampac.dll"]

  chii:
    build:
      context: ./docker/chii
      dockerfile: Dockerfile
    restart: unless-stopped
    expose:
      - "8080"

  nginx:
    image: openresty/openresty:focal
    restart: unless-stopped
    ports:
      - "${LAMPA_STACK_PORT:-80}:80"
    volumes:
      - ./plugins:/app/plugins:ro
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - lampac

  watchtower:
    image: containrrr/watchtower
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    labels: [ "com.centurylinklabs.watchtower.scope=lampac" ]
    command: --schedule "0 0 4 * * *" --include-stopped --cleanup --scope lampac
    environment:
      - WATCHTOWER_DEBUG=true
