services:
  nginx:
    image: nginx:alpine
    # container_name: nginx
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - torrserver
      - qbittorrent
      - lampa

  torrserver:
    image: ghcr.io/dhvcc/torrserver:latest
    restart: unless-stopped
    # container_name: torrserver
    environment:
      - TS_PORT=5665
      - TS_DONTKILL=1
      - TS_HTTPAUTH=0
      - TS_CONF_PATH=/opt/ts/config
      - TS_TORR_DIR=/opt/ts/torrents
      - TS_DOWNLOAD_DIR=/downloads
    volumes:
      - torrserver-cache:/opt/ts/torrents
      - torrserver-config:/opt/ts/config
      - qbittorrent-data:/downloads:ro
    expose:
      - '5665'

  qbittorrent:
    # container_name: qbittorrent
    restart: unless-stopped
    build:
      dockerfile: qBittorrent.patch.Dockerfile
      context: .
    expose:
      - "5666"
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=002
      - TZ=Etc/UTC
      - WEBUI_PORTS=5666/tcp,5666/udp
    # volumes:
      # - qbittorrent-config:/config
      # - qbittorrent-data:/app/qBittorrent/downloads

  lampa:
    # container_name: lampa
    restart: unless-stopped
    image: ghcr.io/dhvcc/lampa:latest
    expose:
      - 3000

volumes:
  torrserver-cache:
  torrserver-config:
  qbittorrent-config:
  qbittorrent-data:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/Users/alexeyartishevsky/Movies/Torr'
