services:
  nginx:
    extends:
      file: docker-compose.yml
      service: nginx

  torrserver:
    extends:
      file: docker-compose.yml
      service: torrserver
    build:
      dockerfile: Dockerfile
      context: ./torrserver
      args:
        - REACT_APP_SERVER_HOST=.
        - PUBLIC_URL=.
    image: '' # Override image with empty string to use build instead

  qbittorrent:
    extends:
      file: docker-compose.yml
      service: qbittorrent

  # jackett:
  #   extends:
  #     file: docker-compose.yml
  #     service: jackett
  #   volumes:
  #     - jackett-blackhole:/downloads
  #     - jackett-config:/config
  #     - ./jackett/config/Jackett/ServerConfig.json:/tmp/config/Jackett/ServerConfig.json:ro
  #     - ./jackett/config/Jackett/Indexers:/tmp/config/Jackett/Indexers:ro

  lampac-api:
    extends:
      file: docker-compose.yml
      service: lampac-api
    volumes:
      - ./lampac-module-manifest.json:/home/module/manifest.json:ro

  lampa:
    extends:
      file: docker-compose.yml
      service: lampa
    build:
      dockerfile: Dockerfile
      context: ./lampa
    image: '' # Override image with empty string to use build instead

  # Test services for nginx proxy debugging
  # echo:
  #   image: mendhak/http-https-echo:35
  #   restart: unless-stopped
  #   expose:
  #     - "8080"
  #     - "8443"

# Can't use extends at top level
volumes:
  torrserver-cache:
  torrserver-config:
  qbittorrent-config:
  qbittorrent-data:
  jackett-blackhole:
  jackett-config:
