services:
  nginx:
    build:
      context: docker/nginx
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "${LAMPA_STACK_PORT:-80}:80"
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./plugins:/app/plugins:ro
      - nginx-passwords:/etc/nginx/pass
    depends_on:
      - torrserver
      - qbittorrent
      - lampa

  torrserver:
    image: ghcr.io/dhvcc/torrserver:latest
    restart: unless-stopped
    environment:
      - TS_PORT=5665
      - TS_DONTKILL=1
      - TS_HTTPAUTH=0
      - TS_CONF_PATH=/opt/ts/config
      - TS_TORR_DIR=/opt/ts/torrents
      - TS_DOWNLOAD_DIR=/downloads
    volumes:
      - torrserver-cache:/opt/ts/torrents
      - torrserver-config:/opt/ts/config
      - qbittorrent-data:/downloads:ro
    expose:
      - '5665'

  qbittorrent:
    restart: unless-stopped
    build:
      dockerfile: Dockerfile
      context: docker/qbittorrent
    expose:
      - "5666"
    environment:
      - PUID=0
      - PGID=0
      - UMASK=002
      - TZ=Etc/UTC
      - WEBUI_PORTS=5666/tcp,5666/udp
    volumes:
      - qbittorrent-config:/config
      - qbittorrent-data:/app/qBittorrent/downloads

  lampac-api:
    # image: ghcr.io/dhvcc/lampac:latest
    image: immisterio/lampac
    restart: unless-stopped
    volumes:
      - ./docker/lampac/manifest.json:/home/module/manifest.json:ro
      - ./docker/lampac/init.conf:/home/init.conf:ro
    expose:
      - "9118"

  lampa:
    restart: unless-stopped
    image: ghcr.io/dhvcc/lampa:latest
    expose:
      - 3000

volumes:
  torrserver-cache:
  torrserver-config:
  nginx-passwords:
  qbittorrent-config:
  qbittorrent-data:
    # Mount data to already existing folder
    # driver: local
    # driver_opts:
    #   type: 'none'
    #   o: 'bind'
    #   device: '/path/to/existing/folder'
