services:
  nginx:
    image: nginx:alpine
    restart: unless-stopped
    ports:
      - "80:80"
      - "9118:9118"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./plugins:/app/plugins:ro
    depends_on:
      - torrserver
      - qbittorrent
      - lampa
      - jackett

  torrserver:
    image: ghcr.io/dhvcc/torrserver:latest
    restart: unless-stopped
    environment:
      - TS_PORT=5665
      - TS_DONTKILL=1
      - TS_HTTPAUTH=0
      - TS_CONF_PATH=/opt/ts/config
      - TS_TORR_DIR=/opt/ts/torrents
      - TS_DOWNLOAD_DIR=/downloads
    volumes:
      - torrserver-cache:/opt/ts/torrents
      - torrserver-config:/opt/ts/config
      - qbittorrent-data:/downloads:ro
    expose:
      - '5665'

  qbittorrent:
    restart: unless-stopped
    build:
      dockerfile: qBittorrent.patch.Dockerfile
      context: .
    expose:
      - "5666"
    environment:
      - PUID=0
      - PGID=0
      - UMASK=002
      - TZ=Etc/UTC
      - WEBUI_PORTS=5666/tcp,5666/udp
    volumes:
      - qbittorrent-config:/config
      - qbittorrent-data:/app/qBittorrent/downloads

  jackett:
    image: linuxserver/jackett:latest
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - AUTO_UPDATE=true
    volumes:
      - jackett-blackhole:/downloads
      - jackett-config:/config
      # Default Server Config and Indexers. Put to tmp to avoid overwriting existing config
      - ./jackett/config/Jackett/ServerConfig.json:/tmp/config/Jackett/ServerConfig.json:ro
      - ./jackett/config/Jackett/Indexers:/tmp/config/Jackett/Indexers:ro
    entrypoint: ["/bin/sh", "-c", "mkdir -p /config/Jackett/Indexers && cp -n /tmp/config/Jackett/Indexers/* /config/Jackett/Indexers/ && cp -n /tmp/config/Jackett/ServerConfig.json /config/Jackett/ServerConfig.json && /init"]
    expose:
      - "9117"

  lampac-api:
    # image: ghcr.io/dhvcc/lampac:latest
    image: immisterio/lampac
    restart: unless-stopped
    expose:
      - "9118"

  lampa:
    restart: unless-stopped
    image: ghcr.io/dhvcc/lampa:latest
    expose:
      - 3000

volumes:
  torrserver-cache:
  torrserver-config:
  qbittorrent-config:
  qbittorrent-data:
  jackett-blackhole:
  jackett-config:
    # Mount data to already existing folder
    # driver: local
    # driver_opts:
    #   type: 'none'
    #   o: 'bind'
    #   device: '/path/to/existing/folder'
